# Generated by Django 5.2.8 on 2026-09-30 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_stock_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
    ]
