# Generated by Django 5.2.8 on 2026-09-30 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_category_description_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
    ]
